on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install github pages 
      run: npm install gh-pages --save-dev   
    - name: Install packages
      run: yarn install
    - name: Build an app
      run: yarn build



