on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install github pages 
      run: yarn global add gh-pages   
    - name: publish to github pages
      run: gh-pages -d public -b main



